---
title: "Report on AQI Bayesian hierarchical modeling"
author: "Michael Andreae"
date: "March 24, 2016"
output: pdf_document
---

we build various random effects model with either insurance status (pay) or median income in the home zip code of the patients as primary predictor and added variables like institution or procedure cpt codes as random effects, sometimes nested.

```{r, packages, message=FALSE, echo=FALSE, warning=FALSE}
library(knitr) # required to set options in Markdown R
library(lme4)
library(rstan)
library(rstanarm)
library(shinystan)
# library(nlme)
```

```{r, global_options, echo=FALSE}
# set options
opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE)
rm(list = ls())
everything <- TRUE
```

```{r cores}
library(parallel)
detectCores()
```

```{r stanfit3.0, eval=everything}
require(rstanarm)
require(knitr)
## model and path
model_name <- "stanfit 3.0" # used in path
model.name <- "stanfit3.0"  # used in R
summary_name <- paste0(model.name, ".summary")
formulary_name <- paste0(model.name, ".formula")
coefficient_name <- paste0(model.name, ".coefficients")

## load
file_path <- file.path("Results", paste0(model_name,".Rdata"))
file_path.summary <- file.path("Results", paste0(model_name,"_summary.Rdata"))

load(file_path)
assign("fit",get(model.name))

## extract summary
summary.fit <- summary(fit, pars="beta", probs=c(0.025, 0.5, 0.975), digits=2)
assign(summary_name, summary.fit)
assign(formulary_name, fit$formula)
assign(coefficient_name, fit$coefficients[1:20])

save(summary_name,formulary_name,coefficient_name, file = file_path.summary)

get(summary_name)
get(formulary_name)
OR.table <- as.data.frame(exp(get(coefficient_name)))
kable(OR.table)
```